version: '3.8'
services:
  # web:
  #   build: .
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     DATABASE_URL: postgres://postgres:password@db:5432/mydb
  #     JWT_SECRET: 'your-secret-key'
  #   depends_on:
  #     - db
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
